export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  PROJECTS: '/projects',
  PROJECT_NEW: '/projects/new',
  PROJECT: (id: string) => `/projects/${id}`,
  PROJECT_BOARD: (id: string) => `/projects/${id}/board`,
  PROJECT_TASKS: (id: string) => `/projects/${id}/tasks`,
  PROJECT_TIMELINE: (id: string) => `/projects/${id}/timeline`,
  PROJECT_MILESTONES: (id: string) => `/projects/${id}/milestones`,
  PROJECT_MEMBERS: (id: string) => `/projects/${id}/members`,
  PROJECT_SETTINGS: (id: string) => `/projects/${id}/settings`,
  TASKS: '/tasks',
  TASK: (id: string) => `/tasks/${id}`,
  TEAMS: '/teams',
  TEAM_NEW: '/teams/new',
  TEAM: (id: string) => `/teams/${id}`,
  TEAM_MEMBERS: (id: string) => `/teams/${id}/members`,
  UPDATES: '/updates',
  UPDATE_NEW: '/updates/new',
  UPDATE: (id: string) => `/updates/${id}`,
  REPORTS: '/reports',
  REPORTS_DAILY: '/reports/daily',
  REPORTS_WEEKLY: '/reports/weekly',
  REPORT_PROJECT: (id: string) => `/reports/project/${id}`,
  REPORT_EMPLOYEE: (id: string) => `/reports/employee/${id}`,
  SEARCH: '/search',
  MEMBERS: '/members',
  MEMBER: (id: string) => `/members/${id}`,
  PROFILE: '/profile',
  BUGS: '/bugs',
  BUG: (id: string) => `/bugs/${id}`,
} as const;
